In [ ]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
import pandas as pd
import numpy as np
import nltk

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
reviews = pd.read_csv('https://raw.githubusercontent.com/nursnaaz/GoogletoChatgpt/main/05.%20Building%20Text%20Classification/Sentiment%20Analysis/movie_reviews.csv')

In [ ]:
reviews.sentiment.value_counts()

positive    25000
negative    25000
Name: sentiment, dtype: int64

In [ ]:
reviews.sample(3000).sentiment.value_counts()

positive    1530
negative    1470
Name: sentiment, dtype: int64

In [ ]:
reviews_sample = reviews.sample(3000)

In [ ]:
reviews_sample.sentiment.value_counts()

negative    1522
positive    1478
Name: sentiment, dtype: int64

In [ ]:
reviews_sample = reviews_sample.reset_index().drop(columns = 'index')

In [ ]:
reviews_sample

review sentiment
0     I believe an entire book can be written about ...  negative
1     I'm not sure how related they are, but I'm alm...  negative
2     I always follow the Dakar, so when my husband ...  positive
3     Must have to agree with the other reviewer. Th...  negative
4     I used to love Sabrina The Teenage Witch and h...  positive
...                                                 ...       ...
2995  ... but I laughed. A lot.<br /><br />I saw 'As...  positive
2996  Get Shorty was an excellent film. It was funny...  negative
2997  to be honest, i didn't watch all of the origin...  negative
2998  Oftentimes, films of this nature come across a...  positive
2999  As always Joan Hickson is wonderful as Jane M....  positive

[3000 rows x 2 columns]

In [ ]:
import nltk
import re
from bs4 import BeautifulSoup

stop_words = nltk.corpus.stopwords.words('english')


def strip_html(doc):
    soup = BeautifulSoup(doc,"html.parser")
    text = soup.get_text()
    return text


def normalize_document(doc):
    doc = strip_html(doc)
    # lower case and remove special characters\whitespaces
    doc = re.sub(r'[^a-zA-Z\s]', '', doc, re.I|re.A)
    doc = doc.lower()
    doc = doc.strip()
    # tokenize document
    tokens = nltk.word_tokenize(doc)
    # filter stopwords out of document
    filtered_tokens = [token for token in tokens if token not in stop_words]
    # re-create document from filtered tokens
    doc = ' '.join(filtered_tokens)
    return doc

In [ ]:
reviews_sample['review_sample'] = reviews_sample['review'].apply(normalize_document)

<ipython-input-10-cd94eacb00e0>:9: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = BeautifulSoup(doc,"html.parser")


In [ ]:
reviews_sample

review sentiment  \
0     I believe an entire book can be written about ...  negative   
1     I'm not sure how related they are, but I'm alm...  negative   
2     I always follow the Dakar, so when my husband ...  positive   
3     Must have to agree with the other reviewer. Th...  negative   
4     I used to love Sabrina The Teenage Witch and h...  positive   
...                                                 ...       ...   
2995  ... but I laughed. A lot.<br /><br />I saw 'As...  positive   
2996  Get Shorty was an excellent film. It was funny...  negative   
2997  to be honest, i didn't watch all of the origin...  negative   
2998  Oftentimes, films of this nature come across a...  positive   
2999  As always Joan Hickson is wonderful as Jane M....  positive   

                                          review_sample  
0     believe entire book written odyssey remake cla...  
1     im sure related im almost certain lost delirio...  
2     always follow dakar husband bought charlies ra...  
3     must agree reviewer got worst movie let alone ...  
4     used love sabrina teenage witch seen every sin...  
...                                                 ...  
2995  laughed loti saw astrix et les vikings public ...  
2996  get shorty excellent film funny perfect balanc...  
2997  honest didnt watch original howling scenes saw...  
2998  oftentimes films nature come across mixed bag ...  
2999  always joan hickson wonderful jane subtle shar...  

[3000 rows x 3 columns]

In [ ]:
X = reviews_sample['review_sample']
y = reviews_sample['sentiment']

In [ ]:
train_X, test_X, train_y, test_y = train_test_split(X,y, test_size=0.33, random_state=23)

In [ ]:
train_X.shape, test_X.shape, train_y.shape, test_y.shape

((2010,), (990,), (2010,), (990,))

# Count Vectorizer

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer(binary=True)

In [ ]:
cv_transfored_train_X = cv.fit_transform(train_X)
cv_transfored_test_X = cv.transform(test_X)

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(cv_transfored_train_X, train_y)

LogisticRegression()

In [ ]:
train_pred = model.predict(cv_transfored_train_X)
test_pred = model.predict(cv_transfored_test_X)

In [ ]:
confusion_matrix(train_y, train_pred)

array([[1028,    0],
       [   0,  982]])

In [ ]:
confusion_matrix(test_y, test_pred)

array([[397,  97],
       [ 81, 415]])

In [ ]:
print("Train Accuracy : ",accuracy_score(train_y, train_pred))
print("Test Accuracy : ",accuracy_score(test_y, test_pred))

Train Accuracy :  1.0
Test Accuracy :  0.8202020202020202


# Bag of Words

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer(binary=False)

In [ ]:
cv_transfored_train_X = cv.fit_transform(train_X)
cv_transfored_test_X = cv.transform(test_X)

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(cv_transfored_train_X, train_y)

LogisticRegression()

In [ ]:
train_pred = model.predict(cv_transfored_train_X)
test_pred = model.predict(cv_transfored_test_X)

In [ ]:
confusion_matrix(train_y, train_pred)

array([[1028,    0],
       [   0,  982]])

In [ ]:
confusion_matrix(test_y, test_pred)

array([[394, 100],
       [ 75, 421]])

In [ ]:
print("Train Accuracy : ",accuracy_score(train_y, train_pred))
print("Test Accuracy : ",accuracy_score(test_y, test_pred))

Train Accuracy :  1.0
Test Accuracy :  0.8232323232323232


# TF - IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tf = TfidfVectorizer()

In [ ]:
tf_transfored_train_X = tf.fit_transform(train_X)
tf_transfored_test_X = tf.transform(test_X)

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(tf_transfored_train_X, train_y)

LogisticRegression()

In [ ]:
train_pred = model.predict(tf_transfored_train_X)
test_pred = model.predict(tf_transfored_test_X)

In [ ]:
confusion_matrix(train_y, train_pred)

array([[1008,   20],
       [  21,  961]])

In [ ]:
confusion_matrix(test_y, test_pred)

array([[400,  94],
       [ 70, 426]])

In [ ]:
print("Train Accuracy : ",accuracy_score(train_y, train_pred))
print("Test Accuracy : ",accuracy_score(test_y, test_pred))

Train Accuracy :  0.9796019900497512
Test Accuracy :  0.8343434343434344


# Word Embeddings

### Glove

In [ ]:
!wget http://nlp.stanford.edu/data/glove.6B.zip

--2024-03-30 05:12:30--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2024-03-30 05:12:30--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2024-03-30 05:12:30--  https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glov

In [ ]:
!unzip glove*.zip

Archive:  glove.6B.zip
  inflating: glove.6B.50d.txt        
  inflating: glove.6B.100d.txt       
  inflating: glove.6B.200d.txt       
  inflating: glove.6B.300d.txt       


In [ ]:
# Load GloVe embeddings into a dictionary
def load_embeddings(file_path):
    embeddings = {}
    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            values = line.split()
            word = values[0]
            vector = np.asarray(values[1:], dtype='float32')
            embeddings[word] = vector
    return embeddings

glove_embeddings_path = 'glove.6B.300d.txt'  # Adjust the path to your downloaded GloVe file
wv = load_embeddings(glove_embeddings_path)

In [ ]:
def average_word_vectors(words, model, vocabulary, num_features):

    feature_vector = np.zeros((num_features,),dtype="float64")
    nwords = 0.

    for word in words:
        if word in vocabulary:
            nwords = nwords + 1.
            feature_vector = np.add(feature_vector, model[word])

    if nwords:
        feature_vector = np.divide(feature_vector, nwords)

    return feature_vector


def averaged_word_vectorizer(corpus, model, num_features):
    vocabulary = set(model.keys())
    features = [average_word_vectors(tokenized_sentence, model, vocabulary, num_features)
                    for tokenized_sentence in corpus]
    return np.array(features)


In [ ]:
normalize_corpus = np.vectorize(normalize_document)
train_norm_corpus = normalize_corpus(train_X)
train_tokenized_corpus = [nltk.word_tokenize(doc) for doc in train_norm_corpus]

test_norm_corpus = normalize_corpus(test_X)
test_tokenized_corpus = [nltk.word_tokenize(doc) for doc in test_norm_corpus]

In [ ]:
# get document level embeddings
feature_size = 300
train_features_X = averaged_word_vectorizer(corpus=train_tokenized_corpus, model=wv,
                                             num_features=feature_size)

test_features_X = averaged_word_vectorizer(corpus=test_tokenized_corpus, model=wv,
                                             num_features=feature_size)

In [ ]:
pd.DataFrame(train_features_X)

0         1         2         3         4         5         6    \
0    -0.100361  0.157201  0.007185  0.046745 -0.004388 -0.008285  0.012053   
1    -0.002740  0.001525 -0.014003  0.019621  0.014668 -0.026539 -0.026830   
2     0.007473  0.044139  0.024967 -0.120772  0.012186  0.049565 -0.071964   
3    -0.085236  0.149263 -0.022318 -0.073964 -0.053262  0.158988 -0.105463   
4     0.007187  0.098442 -0.057280 -0.067986 -0.028238  0.036475 -0.078832   
...        ...       ...       ...       ...       ...       ...       ...   
2005 -0.100892  0.104963  0.030122 -0.092034  0.001261  0.086831 -0.062282   
2006 -0.027546  0.090071 -0.002281 -0.001931 -0.016498  0.054200 -0.066321   
2007 -0.059837  0.021525 -0.080156 -0.023177 -0.039596 -0.079240 -0.026227   
2008 -0.098487  0.029102  0.039672 -0.070932  0.027603  0.063452 -0.011930   
2009 -0.018990  0.016233 -0.028378 -0.115006  0.032024 -0.002126 -0.047361   

           7         8         9    ...       290       291       292  \
0     0.007874 -0.044550 -0.757972  ... -0.009558 -0.050003  0.061013   
1     0.082078 -0.015694 -1.033780  ... -0.028317 -0.099541 -0.078640   
2     0.019214 -0.081501 -0.994460  ...  0.019407 -0.092963 -0.063437   
3     0.022082  0.025037 -1.027409  ...  0.002445  0.021359 -0.091427   
4     0.019994  0.010792 -0.964990  ...  0.020610 -0.148243 -0.027783   
...        ...       ...       ...  ...       ...       ...       ...   
2005  0.016109 -0.011395 -1.090373  ... -0.005751  0.018806  0.011790   
2006  0.071042  0.004490 -0.945924  ...  0.006348 -0.074755 -0.057468   
2007  0.013643 -0.037692 -0.647988  ... -0.072935 -0.018644 -0.039993   
2008  0.004132  0.070241 -0.788056  ... -0.014667 -0.079346 -0.037443   
2009  0.009434  0.047765 -1.082308  ...  0.018018 -0.006057 -0.032199   

           293       294       295       296       297       298       299  
0    -0.139435 -0.097381 -0.258200  0.055353 -0.057528 -0.037838  0.085315  
1     0.040657 -0.074824  0.044580 -0.042437 -0.119698 -0.032489  0.073466  
2    -0.034222 -0.136869 -0.149415 -0.051267  0.024611 -0.027957  0.062647  
3     0.073275 -0.052352 -0.190948  0.020259 -0.005005 -0.024536  0.189608  
4    -0.137102 -0.112228 -0.080029 -0.035411  0.051099 -0.038788  0.064781  
...        ...       ...       ...       ...       ...       ...       ...  
2005  0.030752 -0.034622 -0.122775 -0.026136 -0.046759 -0.060020 -0.009500  
2006  0.036442 -0.034065 -0.117191 -0.032288 -0.056449  0.022459  0.026798  
2007  0.001864 -0.068008  0.135130  0.025880 -0.013281 -0.141361 -0.006531  
2008  0.028760 -0.001375 -0.079099 -0.015343 -0.004804 -0.066371  0.030647  
2009  0.013474  0.042079  0.006853 -0.048693 -0.073539 -0.103794  0.037469  

[2010 rows x 300 columns]

In [ ]:
pd.DataFrame(test_features_X)

0         1         2         3         4         5         6    \
0   -0.087635 -0.014784  0.052824 -0.139782  0.004116  0.060239 -0.058859   
1   -0.100393  0.037191  0.031288 -0.103022  0.009911  0.095623 -0.049063   
2   -0.033260  0.119601 -0.051305  0.009061 -0.026399  0.001646 -0.017972   
3   -0.127742  0.033487  0.015558  0.010129  0.006112  0.053002 -0.063147   
4   -0.067700  0.023666 -0.058909 -0.005498  0.016094  0.090122 -0.072081   
..        ...       ...       ...       ...       ...       ...       ...   
985 -0.071443  0.114785 -0.036579 -0.038351 -0.055787  0.054384  0.030339   
986 -0.102158  0.030459 -0.052722 -0.035480  0.020094  0.049122  0.008645   
987 -0.099057  0.092708  0.011953 -0.138284 -0.045487  0.041554 -0.143539   
988 -0.068645  0.031855  0.002011 -0.102138  0.027675  0.043007 -0.099215   
989 -0.055502 -0.001479  0.009300 -0.043377  0.038401  0.051841 -0.064579   

          7         8         9    ...       290       291       292  \
0    0.027754  0.004609 -1.008573  ...  0.020201 -0.182461 -0.132964   
1   -0.058483 -0.018145 -0.897306  ...  0.028620  0.024649 -0.011086   
2   -0.040137  0.042637 -1.103922  ...  0.056316 -0.099619 -0.070127   
3   -0.102813  0.153855 -1.063331  ... -0.043103 -0.027038 -0.057729   
4   -0.036857  0.073294 -1.025099  ... -0.059415 -0.127623 -0.078605   
..        ...       ...       ...  ...       ...       ...       ...   
985 -0.004456  0.000629 -1.007348  ...  0.037089 -0.100041 -0.008958   
986  0.031244  0.103136 -0.991137  ...  0.043055 -0.036652 -0.023746   
987 -0.028817 -0.000351 -1.122374  ...  0.012855 -0.079131 -0.105940   
988  0.045445  0.039684 -0.979054  ...  0.033093 -0.056145 -0.000378   
989 -0.026541  0.027826 -0.910019  ...  0.019066 -0.013663 -0.081623   

          293       294       295       296       297       298       299  
0    0.102272 -0.016233  0.006946  0.010386 -0.058460 -0.026302  0.025692  
1   -0.004041  0.038296 -0.133145 -0.031199 -0.017288 -0.056983  0.027121  
2   -0.027159  0.005744 -0.227798  0.057052 -0.072546 -0.002821  0.047599  
3    0.018533  0.045067 -0.083111 -0.053278 -0.055003 -0.075118  0.030757  
4    0.038907 -0.102858 -0.134078  0.045899 -0.052558  0.027488  0.116099  
..        ...       ...       ...       ...       ...       ...       ...  
985  0.018186 -0.032306 -0.072818 -0.000260 -0.050647 -0.054198  0.010478  
986 -0.085188  0.008299 -0.065057 -0.005281 -0.013116 -0.004587 -0.051262  
987  0.025196 -0.048213 -0.080422  0.008553 -0.004986 -0.027859  0.089334  
988  0.065669 -0.048297  0.030317 -0.022291 -0.041624 -0.166097  0.049701  
989  0.054093 -0.049807 -0.146562  0.020302  0.090603 -0.034594  0.135363  

[990 rows x 300 columns]

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(train_features_X, train_y)

LogisticRegression()

In [ ]:
train_pred = model.predict(train_features_X)
test_pred = model.predict(test_features_X)

In [ ]:
confusion_matrix(train_y, train_pred)

array([[890, 138],
       [164, 818]])

In [ ]:
confusion_matrix(test_y, test_pred)

array([[402,  92],
       [101, 395]])

In [ ]:
print("Train Accuracy : ",accuracy_score(train_y, train_pred))
print("Test Accuracy : ",accuracy_score(test_y, test_pred))

Train Accuracy :  0.8497512437810946
Test Accuracy :  0.805050505050505


# Glove with Deep Learning Architecture

In [ ]:
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation,Dropout, BatchNormalization
from keras.utils import to_categorical


In [ ]:
y_cat_train = to_categorical(np.asarray(train_y.factorize()[0]))
y_cat_test = to_categorical(np.asarray(test_y.factorize()[0]))

In [ ]:
model = Sequential()
model.add(Dense(64, kernel_initializer = 'he_normal', input_shape = (300,),activation = 'elu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))
model.add(Dense(32, kernel_initializer = 'he_normal', activation = 'elu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))
model.add(Dense(16 ,kernel_initializer = 'he_normal',activation = 'elu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))
model.add(Dense(8 ,kernel_initializer = 'he_normal', activation = 'elu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))
model.add(Dense(4 ,kernel_initializer = 'he_normal', activation = 'elu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))
model.add(Dense(2, kernel_initializer = 'he_normal', activation = 'softmax'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                19264     
                                                                 
 batch_normalization (Batch  (None, 64)                256       
 Normalization)                                                  
                                                                 
 dropout (Dropout)           (None, 64)                0         
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 batch_normalization_1 (Bat  (None, 32)                128       
 chNormalization)                                                
                                                                 
 dropout_1 (Dropout)         (None, 32)                0

In [ ]:
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'] )

In [ ]:
history = model.fit(train_features_X,y_cat_train,epochs = 100, verbose = 1, batch_size=100)

Epoch 1/100
21/21 [==============================] - 5s 9ms/step - loss: 0.7348 - accuracy: 0.6119
Epoch 2/100
21/21 [==============================] - 0s 9ms/step - loss: 0.6313 - accuracy: 0.6975
Epoch 3/100
21/21 [==============================] - 0s 10ms/step - loss: 0.5927 - accuracy: 0.7149
Epoch 4/100
21/21 [==============================] - 0s 9ms/step - loss: 0.5499 - accuracy: 0.7507
Epoch 5/100
21/21 [==============================] - 0s 9ms/step - loss: 0.5247 - accuracy: 0.7637
Epoch 6/100
21/21 [==============================] - 0s 8ms/step - loss: 0.5028 - accuracy: 0.7841
Epoch 7/100
21/21 [==============================] - 0s 8ms/step - loss: 0.4909 - accuracy: 0.7871
Epoch 8/100
21/21 [==============================] - 0s 8ms/step - loss: 0.4818 - accuracy: 0.7861
Epoch 9/100
21/21 [==============================] - 0s 9ms/step - loss: 0.4481 - accuracy: 0.8104
Epoch 10/100
21/21 [==============================] - 0s 9ms/step - loss: 0.4368 - accuracy: 0.8328
Epoch 11

In [ ]:
train_pred = np.argmax(model.predict(train_features_X), axis = 1)
test_pred = np.argmax(model.predict(test_features_X), axis = 1)

31/31 [==============================] - 0s 2ms/step


In [ ]:
train_pred = np.where(train_pred ==0, 'positive', 'negative')
test_pred = np.where(test_pred ==0, 'positive', 'negative')

In [ ]:
print("Train Accuracy : ",accuracy_score(train_y, train_pred))
print("Test Accuracy : ",accuracy_score(test_y, test_pred))

Train Accuracy :  0.9870646766169154
Test Accuracy :  0.793939393939394


In [ ]:
# https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit?resourcekey=0-wjGZdNAUop6WykTtMip30g

In [ ]:
#FastText Embedding Vector Download
#https://fasttext.cc/docs/en/english-vectors.html

# Word2vec Pretraining model

In [ ]:
from gensim.models import Word2Vec, KeyedVectors
from nltk.tokenize import word_tokenize

In [68]:
path_to_model = 'word2vec-google-news-300.bin'

#Load W2V model. This will take some time.
%time w2v_model = KeyedVectors.load_word2vec_format(path_to_model, binary=True)
print('done loading Word2Vec')

FileNotFoundError: [Errno 2] No such file or directory: 'word2vec-google-news-300.bin'

done loading Word2Vec


In [69]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [ ]:
#Inspect the model
print('Shape :',w2v_model.vectors.shape)
word2vec_vocab = w2v_model.index_to_key
word2vec_vocab_lower = [item.lower() for item in word2vec_vocab]
print('Total vocabulary counts :',len(word2vec_vocab))

Shape : (3000000, 300)
Total vocabulary counts : 3000000


In [ ]:
#preprocess the text.
def preprocess_corpus(texts):
    tokenized = []
    for text in texts:
        tokens = word_tokenize(text)
        # Remove punctuation and digit and make word in lowercase
        lower = [token.lower() for token in tokens if token not in punctuation and not token.isdigit()]
        # Remove stopwords
        Stopwords = set(stopwords.words("english"))
        words = [token for token in lower if token not in Stopwords]
        tokenized.append(words)
    return tokenized

In [ ]:
for word in train_tokenized_corpus[0]:
    try:
        word = word.lower()
        embeddings = w2v_model.key_to_index[word]
        print(word,'-->',embeddings)
    except:
        print(word)

story --> 550
documenting --> 20656
rise --> 1027
chinas
first --> 56
emperor --> 30068
efforts --> 763
unify --> 25688
empire --> 10746
expensive --> 2414
movie --> 1121
production --> 620
chinese --> 100038
historyits
worth --> 1069
every --> 274
penny --> 8725
visually --> 20622
dazzling --> 16782
cinematography --> 37101
sweeping --> 6378
score --> 1012
outstanding --> 1890
characters --> 3304
make --> 109
one --> 45
finest --> 8214
epics --> 71594
ever --> 518
put --> 238
film --> 692
foreign --> 754
otherwise --> 2357
please --> 2456
miss --> 2116
opportunity --> 703
see --> 158
big --> 276
screen --> 1973


In [ ]:
# Creating a feature vector by averaging all embeddings for all sentences
def features_embeddings(list_of_lists):

    # feature vector column length
    DIMENSION = w2v_model.vector_size

    # Zero vector if words not in our w2v_model vocubulary
    zero_vector = np.zeros(DIMENSION)

    features = []

    # feature vector for each sentence in list_of_lists one by one
    for tokens in list_of_lists:

        # feature vector for a single sentence
        feature =  np.zeros(DIMENSION) # shape = 1X DIMENSION

        # count for each token/word in a tokens or sentence
        feature_counts = 0 + 1e-5   # to avoid divide-by-zero
        for token in tokens:
            if token in w2v_model:
                feature += w2v_model[token] # Here both feature and w2v_model[token] are of same shape : 1X DIMENSION
                feature_counts +=1    # Count increases for each token in a tokens

        # Average the feature values for each tokens
        if(feature_counts !=0 ):        # for non empty tokens
            features.append(feature/feature_counts)
        else:                           # for empty tokens
            features.append(zero_vector)

    return features

In [ ]:
train_vectors = features_embeddings(train_tokenized_corpus)
print(len(train_vectors))
train_vectors[0].shape

2010


(300,)

In [ ]:
test_vectors = features_embeddings(test_tokenized_corpus)
print(len(test_vectors))
test_vectors[0].shape

990


(300,)

In [ ]:
pd.DataFrame(train_vectors)

0         1         2         3         4         5         6    \
0     0.025413  0.017893  0.009669  0.100787  0.006266  0.008118  0.087102   
1     0.041864  0.029539 -0.003314  0.060085 -0.037326  0.024126  0.069229   
2     0.058087  0.059167 -0.002032  0.059178 -0.067313 -0.008359  0.055403   
3     0.055705  0.011109 -0.012106  0.110000 -0.038259 -0.005965  0.032449   
4     0.055795  0.065975  0.007370  0.097802 -0.042695 -0.013492  0.041037   
...        ...       ...       ...       ...       ...       ...       ...   
2005  0.077894  0.048710 -0.000583  0.103553 -0.087790  0.059894  0.082951   
2006  0.044526  0.053642  0.012405  0.116098 -0.079652  0.042850  0.064464   
2007  0.051548  0.046371  0.011113  0.081187 -0.054934  0.000628  0.046997   
2008  0.046670  0.050964 -0.023507  0.095043 -0.012921 -0.019055  0.035108   
2009  0.031206  0.053334  0.012577  0.081815 -0.034789 -0.017460  0.038583   

           7         8         9    ...       290       291       292  \
0    -0.022144  0.094054  0.093803  ... -0.134564  0.016229 -0.099295   
1    -0.044021  0.081423  0.041232  ... -0.137162  0.055503 -0.123243   
2    -0.065988  0.090547  0.091691  ... -0.106429  0.020701 -0.087849   
3    -0.006873  0.073128  0.077147  ... -0.070112  0.076626 -0.136963   
4    -0.053537  0.053832  0.062231  ... -0.048031  0.038145 -0.087831   
...        ...       ...       ...  ...       ...       ...       ...   
2005 -0.036448  0.093953  0.095390  ... -0.098446  0.056713 -0.084245   
2006 -0.086374  0.069077  0.077816  ... -0.031583  0.085157 -0.107991   
2007 -0.069626  0.075349  0.078323  ... -0.056852  0.055989 -0.086515   
2008 -0.045781  0.077376  0.050663  ... -0.039909  0.045488 -0.077940   
2009 -0.073359  0.049860  0.069712  ... -0.027770  0.056752 -0.099040   

           293       294       295       296       297       298       299  
0     0.033675 -0.013184 -0.042983 -0.013791 -0.068369  0.027123 -0.027254  
1    -0.004244 -0.045488 -0.014705  0.026503 -0.036409  0.060550 -0.020487  
2     0.028960 -0.039412 -0.018355  0.006856 -0.051078  0.029464 -0.021360  
3     0.027219 -0.047677 -0.033622  0.011968 -0.064334 -0.002256  0.021236  
4     0.019510 -0.049447 -0.020297  0.035594 -0.054443  0.001766 -0.020204  
...        ...       ...       ...       ...       ...       ...       ...  
2005 -0.011151 -0.068074 -0.021399  0.044470 -0.062348  0.042190  0.017638  
2006  0.040527 -0.072522 -0.061935  0.003120 -0.048855 -0.002187 -0.013914  
2007  0.009794 -0.051231  0.006207  0.023844 -0.069063  0.019625  0.010695  
2008 -0.015282 -0.033841 -0.007587  0.033654 -0.057930  0.020167  0.016718  
2009  0.010804 -0.059935  0.014052  0.032139 -0.026255  0.042523  0.019454  

[2010 rows x 300 columns]

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(train_vectors, train_y)

LogisticRegression()

In [ ]:
train_pred = model.predict(train_vectors)
test_pred = model.predict(test_vectors)

In [ ]:
confusion_matrix(train_y, train_pred)

array([[885, 147],
       [175, 803]])

In [ ]:
confusion_matrix(test_y, test_pred)

array([[427,  67],
       [118, 378]])

In [ ]:
print("Train Accuracy : ",accuracy_score(train_y, train_pred))
print("Test Accuracy : ",accuracy_score(test_y, test_pred))

Train Accuracy :  0.8398009950248756
Test Accuracy :  0.8131313131313131


# Word2vec Training

In [ ]:
# Creating a feature vector by averaging all embeddings for all sentences
def features_embeddings_trained(list_of_lists):

    # feature vector column length
    DIMENSION = w2v_model.vector_size

    # Zero vector if words not in our w2v_model vocubulary
    zero_vector = np.zeros(DIMENSION)

    features = []

    # feature vector for each sentence in list_of_lists one by one
    for tokens in list_of_lists:

        # feature vector for a single sentence
        feature =  np.zeros(DIMENSION) # shape = 1X DIMENSION

        # count for each token/word in a tokens or sentence
        feature_counts = 0 + 1e-5   # to avoid divide-by-zero
        for token in tokens:
            if token in w2v_model.wv.index_to_key:
                feature += w2v_model.wv[token] # Here both feature and w2v_model[token] are of same shape : 1X DIMENSION
                feature_counts +=1    # Count increases for each token in a tokens

        # Average the feature values for each tokens
        if(feature_counts !=0 ):        # for non empty tokens
            features.append(feature/feature_counts)
        else:                           # for empty tokens
            features.append(zero_vector)

    return features

In [ ]:
tokenized_corpus = train_tokenized_corpus + test_tokenized_corpus

In [ ]:
from gensim.models import Word2Vec


w2v_model = Word2Vec(tokenized_corpus, vector_size=100, window=5, min_count=5, workers=4, epochs=1000)

In [ ]:
w2v_model.wv.get_vector('good')

array([-1.2162328e+00,  2.8214784e+00, -1.6183339e+00, -6.6693825e-01,
        3.1950185e+00, -2.5314000e-01, -1.1005534e+00,  2.3824410e+00,
        2.1774043e-01, -9.0693676e-01, -1.3202015e+00, -3.0586648e+00,
       -1.6025095e+00, -4.2471405e-02,  1.1779610e+00, -2.2992020e+00,
        1.6685644e+00, -1.5037817e+00,  3.1916767e-01, -4.8470378e+00,
       -1.1382118e+00,  1.4438250e+00,  1.3072069e+00,  1.6388686e+00,
        5.8727002e-01,  7.9172087e-01,  8.9846438e-01,  1.4334803e+00,
       -3.8484967e+00,  6.4467245e-01,  5.3743535e-01,  3.1226642e+00,
       -1.0429981e+00, -2.4385281e+00,  8.3032900e-01,  7.8326362e-01,
        7.4336153e-01, -8.4292746e-01, -4.3271947e-01, -1.9767152e+00,
       -1.6679970e+00, -1.3975409e-01, -1.6176885e-01,  3.8531470e-01,
        2.1063437e+00, -2.9386628e+00, -1.9809042e+00,  5.2611160e-01,
        6.8800747e-01,  4.0107608e+00,  7.9448837e-05, -2.0757146e+00,
        1.2549385e+00, -9.0661758e-01, -1.4107471e+00, -2.2575657e-01,
      

In [ ]:
train_vectors = features_embeddings_trained(train_tokenized_corpus)
print(len(train_vectors))
train_vectors[0].shape

2010


(100,)

In [ ]:
test_vectors = features_embeddings_trained(test_tokenized_corpus)
print(len(test_vectors))
test_vectors[0].shape

990


(100,)

In [ ]:
pd.DataFrame(train_vectors)

0         1         2         3         4         5         6   \
0    -0.542037  0.207305  1.294649  0.187143  0.488779  0.268629 -0.910947   
1    -0.547686  0.355771  0.166179 -0.678580  0.351975 -0.926832 -0.048489   
2     0.116587 -0.036734  0.051043  0.324732  0.158343 -0.727407  0.036239   
3    -0.228311  0.485657  0.002040 -1.189860  0.235160  0.173281  0.261406   
4    -0.905322  0.684515  0.226590 -0.571770  1.019778 -0.274504  0.277069   
...        ...       ...       ...       ...       ...       ...       ...   
2005  0.416515  1.469960 -0.865980 -0.318793  0.090127 -0.181142 -0.393172   
2006 -0.801499  0.963594  1.378747  0.715873 -0.079275 -0.527411 -0.051364   
2007 -0.084227  0.398447  0.062124 -0.537270  0.218859  0.075756 -0.187547   
2008 -0.035457  0.467487  0.638060 -0.615420 -0.076184 -0.966929 -0.580523   
2009 -0.474222  0.218642  0.875947 -1.075327  1.048074 -0.261274  0.521157   

            7         8         9   ...        90        91        92  \
0     0.615916  0.199186  1.611569  ... -0.178649 -0.064968  0.608629   
1     0.668812 -0.215949  0.300916  ...  0.782023 -0.358429  0.202502   
2     0.835853  0.013212 -0.186487  ...  0.489580  0.111286 -0.297007   
3     1.065048 -0.415442  0.322661  ...  0.660357  0.203004  1.263204   
4     0.826453 -0.102960 -0.080917  ...  0.302292 -0.411636  0.831800   
...        ...       ...       ...  ...       ...       ...       ...   
2005  1.767932 -0.033844  0.087816  ...  0.204167 -0.771697 -0.384556   
2006  1.312657 -0.351139 -0.641406  ...  0.463297 -0.044615  0.106691   
2007 -0.189401 -0.381424  0.118413  ...  0.019469  0.049975  0.154613   
2008  0.349052  0.073621  0.165564  ...  0.978257 -1.152258  0.020195   
2009 -0.936941 -0.114306 -0.966114  ...  0.222775  0.602532  0.009938   

            93        94        95        96        97        98        99  
0     0.062858  0.090038  1.146683  0.547711  0.386943 -0.177861  0.488217  
1    -0.425116  0.637140  0.518589  0.706520 -0.911478  0.039270  0.930268  
2     0.147138  0.424103  0.587565  0.367007 -0.434915  0.163814  0.683255  
3     0.071106  1.013812  0.558073  0.958466 -1.139623  1.354658  0.349583  
4     0.003049  1.002412  0.173870  0.225041  0.049867  0.011661 -0.309264  
...        ...       ...       ...       ...       ...       ...       ...  
2005  0.934168 -0.252340  0.406547  0.643272 -0.235321 -0.125435 -0.524991  
2006 -0.112504  0.669756  0.821823  1.140819  0.016741  0.731739  0.154779  
2007  0.189762 -0.318999  0.190289 -0.010788  0.303954 -0.456986  0.004394  
2008  0.117045  0.458258 -0.055478 -0.830837  0.583896  0.226798  0.588833  
2009 -0.006009  1.808176 -0.448657  0.224174  0.818366  0.100349  1.167305  

[2010 rows x 100 columns]

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(train_vectors, train_y)

LogisticRegression()

In [ ]:
train_pred = model.predict(train_vectors)
test_pred = model.predict(test_vectors)

In [ ]:
confusion_matrix(train_y, train_pred)

array([[877, 155],
       [161, 817]])

In [ ]:
confusion_matrix(test_y, test_pred)

array([[397,  97],
       [106, 390]])

In [ ]:
print("Train Accuracy : ",accuracy_score(train_y, train_pred))
print("Test Accuracy : ",accuracy_score(test_y, test_pred))

Train Accuracy :  0.8427860696517413
Test Accuracy :  0.794949494949495


# Fasttext Taining Model

In [ ]:
from gensim.models.fasttext import FastText

In [ ]:
# Creating a feature vector by averaging all embeddings for all sentences
def features_embeddings_trained(list_of_lists):

    # feature vector column length
    DIMENSION = w2v_model.vector_size

    # Zero vector if words not in our w2v_model vocubulary
    zero_vector = np.zeros(DIMENSION)

    features = []

    # feature vector for each sentence in list_of_lists one by one
    for tokens in list_of_lists:

        # feature vector for a single sentence
        feature =  np.zeros(DIMENSION) # shape = 1X DIMENSION

        # count for each token/word in a tokens or sentence
        feature_counts = 0 + 1e-5   # to avoid divide-by-zero
        for token in tokens:
            if token in w2v_model.wv.index_to_key:
                feature += w2v_model.wv[token] # Here both feature and w2v_model[token] are of same shape : 1X DIMENSION
                feature_counts +=1    # Count increases for each token in a tokens

        # Average the feature values for each tokens
        if(feature_counts !=0 ):        # for non empty tokens
            features.append(feature/feature_counts)
        else:                           # for empty tokens
            features.append(zero_vector)

    return features

In [ ]:
tokenized_corpus = train_tokenized_corpus + test_tokenized_corpus

In [ ]:
w2v_model = FastText(tokenized_corpus, vector_size=300, window=5, min_count=1, workers=4, epochs=100)

In [ ]:
w2v_model.wv.get_vector('good')

array([-0.39554578,  0.30556968, -0.3278093 ,  0.6070886 , -1.1435615 ,
        0.6960136 ,  1.8225309 , -0.08764059,  0.02879203,  1.8186275 ,
       -2.6683233 , -1.1544572 , -3.6363158 ,  1.4927639 ,  0.25606278,
        1.6747531 , -0.02730703, -0.19937731,  0.5704363 ,  0.37684003,
       -1.1360894 ,  0.10065033,  0.06069138, -1.2784314 ,  0.1724576 ,
       -1.0831739 , -1.2671391 ,  0.96431136,  2.237326  ,  0.36201993,
        0.33683383, -0.8974773 , -2.0102575 , -1.2174679 ,  0.2255754 ,
        0.07015803,  3.3393335 , -1.8132381 ,  1.234856  ,  2.253016  ,
       -0.3265842 ,  1.464262  , -0.5921297 , -3.4554558 ,  2.0791218 ,
        0.12724856, -0.79863393, -2.32285   , -0.89043736,  0.01599858,
       -0.14147553,  0.27829286, -0.19791688,  0.8342646 ,  0.5525431 ,
        0.09347764,  0.06730296,  0.73783684,  0.7105636 ,  1.0975491 ,
        1.3238546 ,  0.13173565,  2.3809848 ,  1.056398  ,  2.9809813 ,
       -3.7532227 ,  5.270201  ,  1.7451004 , -1.5945438 , -0.32

In [ ]:
train_vectors = features_embeddings_trained(train_tokenized_corpus)
print(len(train_vectors))
train_vectors[0].shape

2010


(300,)

In [ ]:
test_vectors = features_embeddings_trained(test_tokenized_corpus)
print(len(test_vectors))
test_vectors[0].shape

990


(300,)

In [ ]:
pd.DataFrame(train_vectors)

0         1         2         3         4         5         6    \
0     0.071765 -0.501332  0.266866 -0.539072  0.543804  0.260111  0.175274   
1     0.201421 -0.835796  0.167064 -0.570961  0.463955  0.147549  0.522221   
2     0.100804 -0.761593  0.050553 -0.359987  0.032850  0.450145 -0.044176   
3    -0.059055 -0.613561 -0.352019 -0.197341  0.321426 -0.136975  0.484984   
4    -0.247734 -0.122627 -0.234251  0.113897  0.412909  0.203975  0.196843   
...        ...       ...       ...       ...       ...       ...       ...   
2005  0.145286 -0.660611  0.096615  0.059080  0.418366 -0.048677  0.231591   
2006 -0.132375  0.007622 -0.060736 -0.169088 -0.065853 -0.240801 -0.004792   
2007  0.061875 -0.504767  0.128449 -0.309454  0.239758  0.448429  0.053110   
2008  0.481774 -0.456385  0.371910 -0.351619  0.140414  0.081677  0.249063   
2009  0.090497 -0.427850 -0.135858  0.034596  0.162196  0.173130  0.077221   

           7         8         9    ...       290       291       292  \
0    -0.025657  0.591547 -0.472240  ...  0.123862 -0.184058 -0.063175   
1    -0.085878  0.511895 -0.483975  ...  0.113176 -0.324834 -0.197113   
2    -0.275377  0.272777 -0.240959  ...  0.334790 -0.360708  0.444338   
3    -0.339944  0.397234 -0.211405  ...  0.324440 -0.049765 -0.042620   
4     0.114238 -0.100210  0.260022  ...  0.590531 -0.380305 -0.021766   
...        ...       ...       ...  ...       ...       ...       ...   
2005 -0.360000  0.168896  0.012134  ...  0.323186  0.065004 -0.259029   
2006 -0.474806  0.204424 -0.280626  ...  0.336286 -0.373046 -0.101730   
2007 -0.022847  0.268978 -0.157851  ...  0.119790 -0.248116  0.137337   
2008 -0.453577  0.048269 -0.103956  ... -0.006385 -0.106864 -0.074057   
2009  0.105850  0.017096 -0.203091  ...  0.327679 -0.256625 -0.110307   

           293       294       295       296       297       298       299  
0     1.502401  0.105758  0.561694  0.195198 -0.154106 -0.705223  0.553513  
1     1.404224  0.185555  0.433111  0.254629  0.201344 -0.938394  0.258309  
2     0.911963 -0.183864  0.532553  0.163177  0.660180 -0.567780  0.196322  
3     0.549133  0.031745  0.500848  0.243917  0.154506 -0.393167  0.501330  
4     0.510044 -0.107208  0.132068 -0.025983  0.021583  0.103656  0.356382  
...        ...       ...       ...       ...       ...       ...       ...  
2005  1.012612 -0.184087  0.426128  0.422127  0.025579 -0.266824 -0.152251  
2006  0.558735  0.085740  0.723193  0.238508  0.306485 -0.265801  0.111616  
2007  0.471121 -0.248154  0.209134  0.027269  0.123677 -0.271872  0.236434  
2008  0.126658 -0.418518  0.317682  0.147618  0.253540 -0.325074 -0.163294  
2009  0.808485 -0.455304  0.315116  0.066056  0.077143 -0.345132  0.177106  

[2010 rows x 300 columns]

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(train_vectors, train_y)

/opt/homebrew/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
train_pred = model.predict(train_vectors)
test_pred = model.predict(test_vectors)

In [ ]:
confusion_matrix(train_y, train_pred)

array([[917, 115],
       [110, 868]])

In [ ]:
confusion_matrix(test_y, test_pred)

array([[403,  91],
       [113, 383]])

In [ ]:
print("Train Accuracy : ",accuracy_score(train_y, train_pred))
print("Test Accuracy : ",accuracy_score(test_y, test_pred))

Train Accuracy :  0.8880597014925373
Test Accuracy :  0.793939393939394


# Fasttext Pre trained

In [ ]:
import fasttext.util
fasttext.util.download_model('en', if_exists='ignore')  # English
ft = fasttext.load_model('cc.en.300.bin')

In [ ]:
ft

In [ ]:
ft.get_dimension()

300

In [ ]:
ft.get_word_vector('good')

array([-0.09213716, -0.0634383 ,  0.00173813,  0.13524324, -0.06561062,
        0.00619071,  0.12609869, -0.01646539,  0.0174491 , -0.00126792,
       -0.09709831,  0.02329333,  0.00996784,  0.00463419,  0.01587938,
        0.00689824,  0.08575399, -0.01988525, -0.0601579 , -0.02327966,
        0.01183712,  0.08217917,  0.01488847,  0.00902181,  0.00696296,
       -0.06426616,  0.03345198, -0.02101481,  0.06767873,  0.03022419,
        0.07203474, -0.05689922, -0.04370377,  0.00642597,  0.0439174 ,
        0.0604848 , -0.00611545, -0.12256738, -0.03530414, -0.02696739,
       -0.02058216,  0.00752347, -0.00686451,  0.0362783 , -0.03308735,
        0.05801626,  0.00832448, -0.06336953, -0.05775082,  0.01089846,
       -0.0925179 ,  0.01559984, -0.04079024,  0.0066871 , -0.06374165,
        0.05881973,  0.07209535, -0.05387195, -0.14658651, -0.04046486,
       -0.02507038, -0.04954465, -0.05224417, -0.06846938,  0.0467079 ,
        0.00459271, -0.07522177,  0.03627685, -0.0698283 ,  0.01

In [ ]:
# Creating a feature vector by averaging all embeddings for all sentences
def features_embeddings_pretrained_fasttext(w2v_model, list_of_lists):

    # feature vector column length
    DIMENSION = w2v_model.get_dimension()

    # Zero vector if words not in our w2v_model vocubulary
    zero_vector = np.zeros(DIMENSION)

    features = []

    # feature vector for each sentence in list_of_lists one by one
    for tokens in list_of_lists:

        # feature vector for a single sentence
        feature =  np.zeros(DIMENSION) # shape = 1X DIMENSION

        # count for each token/word in a tokens or sentence
        feature_counts = 0 + 1e-5   # to avoid divide-by-zero
        for token in tokens:
            feature += w2v_model.get_word_vector(token) # Here both feature and w2v_model[token] are of same shape : 1X DIMENSION
            feature_counts +=1    # Count increases for each token in a tokens

        # Average the feature values for each tokens
        if(feature_counts !=0 ):        # for non empty tokens
            features.append(feature/feature_counts)
        else:                           # for empty tokens
            features.append(zero_vector)
    return features

In [ ]:
train_vectors = features_embeddings_pretrained_fasttext(ft, train_tokenized_corpus)
print(len(train_vectors))
train_vectors[0].shape

2010


(300,)

In [ ]:
test_vectors = features_embeddings_pretrained_fasttext(ft, test_tokenized_corpus)
print(len(test_vectors))
test_vectors[0].shape

990


(300,)

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(train_vectors, train_y)

LogisticRegression()

In [ ]:
train_pred = model.predict(train_vectors)
test_pred = model.predict(test_vectors)

In [ ]:
confusion_matrix(train_y, train_pred)

array([[834, 198],
       [260, 718]])

In [ ]:
confusion_matrix(test_y, test_pred)

array([[402,  92],
       [143, 353]])

In [ ]:
print("Train Accuracy : ",accuracy_score(train_y, train_pred))
print("Test Accuracy : ",accuracy_score(test_y, test_pred))

Train Accuracy :  0.7721393034825871
Test Accuracy :  0.7626262626262627
