In [2]:
!pip install wikipedia

  Preparing metadata (setup.py) ... done
  Created wheel for wikipedia: filename=wikipedia-1.4.0-py3-none-any.whl size=11679 sha256=9fe35fcd222097ccb57a426178699ac8c3dbb11e4af28fb0f05438865a813447
  Stored in directory: /Users/m.alaudeen/Library/Caches/pip/wheels/8f/ab/cb/45ccc40522d3a1c41e1d2ad53b8f33a62f394011ec38cd71c6
Successfully built wikipedia

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python3.11 -m pip install --upgrade pip


In [1]:
import wikipedia

In [11]:
q1 = wikipedia.page('honda motor').content
q2 = wikipedia.page('Hyundai Motor Group').content
q3 = wikipedia.page('dell corporation').content
q4 = wikipedia.page('Hewlett-Packard').content
q5 = wikipedia.page('biryani').content

In [14]:
# Evaluation Metric
# q1 more similar q2
# q3 more similar q5

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
import pandas as pd

In [16]:
#Bag Of Words (BOW)
cv = CountVectorizer()
X = np.array(cv.fit_transform([q1, q2, q3, q4, q5]).todense())

In [17]:
X

array([[15,  0,  1, ...,  0,  0,  1],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [12,  1,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  1,  1,  0]])

In [18]:
cv.get_feature_names_out()

array(['000', '00537897', '007', ..., 'ထမင', 'နတ', '本田技研工業株式会社'],
      dtype=object)

In [19]:
pd.DataFrame(X, columns=cv.get_feature_names_out())

000  00537897  007  01  05  07  10  100  1000  104  ...  ˈhjəːndɛ  برشتن  \
0   15         0    1   1   0   0   0   10     0    0  ...         0      0   
1    0         0    0   1   0   0   0    0     0    0  ...         1      0   
2    0         0    0   0   2   0   1    0     0    0  ...         0      0   
3   12         1    0   0   0   2   4    4     4    1  ...         0      0   
4    0         0    0   0   0   0   0    0     0    0  ...         0      1   

   برنج  برياني  بریان  پلو  าวหมก  ထမင  နတ  本田技研工業株式会社  
0     0       0      0    0      0    0   0           1  
1     0       0      0    0      0    0   0           0  
2     0       0      0    0      0    0   0           0  
3     0       0      0    0      0    0   0           0  
4     1       1      2    1      1    1   1           0  

[5 rows x 4602 columns]

# Euclidean Distance

In [20]:
def euclidean_distance(x,y):
    return np.sqrt(np.sum((x - y)**2))
    

In [21]:
x = np.array([1,3])
y = np.array([2,1])

In [22]:
(1-2)**2 + (3-1)**2

5

In [23]:
np.sqrt(5)

2.23606797749979

In [24]:
euclidean_distance(x,y)

2.23606797749979

In [25]:
X[0]

array([15,  0,  1, ...,  0,  0,  1])

In [26]:
X[1]

array([0, 0, 0, ..., 0, 0, 0])

In [28]:
# Distance Between HONDA and Others
print("Honda - Hyndai ",euclidean_distance(X[0],X[1]))
print("Honda - DELL ",euclidean_distance(X[0],X[2]))
print("Honda - HP ",euclidean_distance(X[0],X[3]))
print("Honda - Biryani ",euclidean_distance(X[0],X[4]))


Honda - Hyndai  886.0445812711683
Honda - DELL  880.1880480897249
Honda - HP  566.3947386761286
Honda - Biryani  680.359463813064


In [31]:
# Distance Between DELL and others
print("DELL - HONDA",euclidean_distance(X[2],X[0]))
print("DELL - HYNDAI ",euclidean_distance(X[2],X[1]))
print("DELL - HP ",euclidean_distance(X[2],X[3]))
print("DELL - BIRYANI ",euclidean_distance(X[2],X[4]))

DELL - HONDA 880.1880480897249
DELL - HYNDAI  63.29296959378664
DELL - HP  690.761898196477
DELL - BIRYANI  400.1949524919074


In [32]:
print("HONDA : ",len(q1.split(' ')))
print("HYNDAI : ",len(q2.split(' ')))
print("DELL : ",len(q3.split(' ')))
print("HP : ",len(q4.split(' ')))
print("BIRYANI : ",len(q5.split(' ')))

HONDA :  8474
HYNDAI :  604
DELL :  676
HP :  7611
BIRYANI :  4196


In [ ]:
# Whenever the document size is higher the distance will be prioritized or higher

# Cosine Similarity 

In [33]:
def cosine_similarity(x, y):
    return np.dot(x,y)/(np.sqrt(np.dot(x,x)) * np.sqrt(np.dot(y,y)))

In [34]:
x = np.array([1,3])
y = np.array([2,1])

In [35]:
1*2 + 3*1

5

In [36]:
np.dot(x,y)

5

In [37]:
1**2 + 3**2

10

In [38]:
np.dot(x,x) 

10

In [39]:
np.dot(y,y) 

5

In [46]:
np.sqrt(np.dot(x,x)) *  np.sqrt(np.dot(y,y) )

7.071067811865476

In [47]:
np.sqrt(10 + 5)

3.872983346207417

In [53]:
5/7.071067811865476

0.7071067811865475

In [52]:
cosine_similarity(x, y)

0.7071067811865475

In [44]:
# Distance Between HONDA and Others
print("Honda - Hyndai ",cosine_similarity(X[0],X[1]))
print("Honda - DELL ",cosine_similarity(X[0],X[2]))
print("Honda - HP ",cosine_similarity(X[0],X[3]))
print("Honda - Biryani ",cosine_similarity(X[0],X[4]))

Honda - Hyndai  0.7223516293224359
Honda - DELL  0.6886797462032319
Honda - HP  0.7939763176815907
Honda - Biryani  0.7268147748697233


In [45]:
# Distance Between DELL and others
print("DELL - HONDA",cosine_similarity(X[2],X[0]))
print("DELL - HYNDAI ",cosine_similarity(X[2],X[1]))
print("DELL - HP ",cosine_similarity(X[2],X[3]))
print("DELL - BIRYANI ",cosine_similarity(X[2],X[4]))

DELL - HONDA 0.6886797462032319
DELL - HYNDAI  0.6141084209403155
DELL - HP  0.7558227324853434
DELL - BIRYANI  0.6467220710388738
