In [2]:
!pip install wikipedia

  Preparing metadata (setup.py) ... done
  Created wheel for wikipedia: filename=wikipedia-1.4.0-py3-none-any.whl size=11679 sha256=9fe35fcd222097ccb57a426178699ac8c3dbb11e4af28fb0f05438865a813447
  Stored in directory: /Users/m.alaudeen/Library/Caches/pip/wheels/8f/ab/cb/45ccc40522d3a1c41e1d2ad53b8f33a62f394011ec38cd71c6
Successfully built wikipedia

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python3.11 -m pip install --upgrade pip


In [3]:
import wikipedia

In [9]:
q1 = wikipedia.page('machinelearning').content
q2 = wikipedia.page('Artificial Intelligence').content
q3 = wikipedia.page('Soccer').content
q4 = wikipedia.page('Cricket').content
q5 = wikipedia.page('Football').content

In [ ]:
# Evaluation Metric
# q1 more similar q2
# q3 more similar q5

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
import pandas as pd

In [23]:
#Bag Of Words (BOW)
cv = CountVectorizer()
X = np.array(cv.fit_transform([q1, q2, q3, q4, q5]).todense())

In [24]:
X

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 1, 2]])

In [25]:
cv.get_feature_names_out()

array(['000', '0070087705', '0134610993', ..., 'φαινίνδα', 'ἐπίσκυρος',
       '蹴鞠'], dtype=object)

In [27]:
pd.DataFrame(X, columns=cv.get_feature_names_out())

000  0070087705  0134610993  0465065707  07  10  100  105  106  11  ...  \
0    1           0           0           1   0   2    0    0    0   0  ...   
1    1           1           1           0   0   1    0    0    0   1  ...   
2    1           0           0           0   1   0    3    1    0   1  ...   
3    0           0           0           0   0   4    2    1    0   2  ...   
4    1           0           0           0   0   1    0    0    1   1  ...   

   zalta  zealand  zeros  zimbabwe  zones  zürich  čapek  φαινίνδα  ἐπίσκυρος  \
0      0        0      1         0      0       0      0         0          0   
1      1        0      0         0      0       0      1         0          0   
2      0        1      0         0      0       1      0         0          0   
3      0        5      0         2      0       0      0         0          0   
4      0        8      0         0      1       0      0         1          1   

   蹴鞠  
0   0  
1   0  
2   1  
3   0  
4   2  

[5 rows x 6603 columns]

# Euclidean Distance

In [31]:
def euclidean_distance(x,y):
    return np.sqrt(np.sum((x - y)**2))
    

In [33]:
x = np.array([1,3])
y = np.array([2,1])

In [34]:
(1-2)**2 + (3-1)**2

5

In [35]:
np.sqrt(5)

2.23606797749979

In [37]:
euclidean_distance(x,y)

2.23606797749979

In [38]:
X[0]

array([1, 0, 0, ..., 0, 0, 0])

In [39]:
X[1]

array([1, 1, 1, ..., 0, 0, 0])

In [43]:
# Distance Between Machine Learning and Others
print("ML - AI ",euclidean_distance(X[0],X[1]))
print("ML - Soccer ",euclidean_distance(X[0],X[2]))
print("ML - Cricket ",euclidean_distance(X[0],X[3]))
print("ML - Football ",euclidean_distance(X[0],X[4]))


ML - AI  413.32190844425367
ML - Soccer  492.9482731484106
ML - Cricket  618.920835002345
ML - Football  691.0332842924428


In [44]:
# Distance Between Artificial Intelligence and others
print("AI ",euclidean_distance(X[1],X[0]))
print("AI - Soccer ",euclidean_distance(X[1],X[2]))
print("AI - Cricket ",euclidean_distance(X[1],X[3]))
print("AI - Football ",euclidean_distance(X[1],X[4]))

AI  413.32190844425367
AI - Soccer  500.4867630617217
AI - Cricket  544.8687915452673
AI - Football  626.2986508048696


In [45]:
# Distance Between Soccer and others
print("Soccer - ML ",euclidean_distance(X[2],X[0]))
print("Soccer - AI ",euclidean_distance(X[2],X[1]))
print("Soccer - Cricket ",euclidean_distance(X[2],X[3]))
print("Soccer - Football ",euclidean_distance(X[2],X[4]))

Soccer - ML  492.9482731484106
Soccer - AI  500.4867630617217
Soccer - Cricket  373.6723163414705
Soccer - Football  410.53501677688837


In [49]:
print("ML : ",len(q1.split(' ')))
print("AI : ",len(q2.split(' ')))
print("Soccer : ",len(q3.split(' ')))
print("Cricket : ",len(q4.split(' ')))
print("Football : ",len(q5.split(' ')))

ML :  8323
AI :  10539
Soccer :  7178
Cricket :  8904
Football :  10100


In [ ]:
# Whenever the document size is higher the distance will be prioritized or higher

# Cosine Similarity 

In [71]:
def cosine_similarity(x, y):
    return np.dot(x,y)/(np.sqrt(np.dot(x,x)) * np.sqrt(np.dot(y,y)))

In [51]:
x = np.array([1,3])
y = np.array([2,1])

In [53]:
1*2 + 3*1

5

In [52]:
np.dot(x,y)

5

In [55]:
1**2 + 3**2

10

In [54]:
np.dot(x,x) 

10

In [56]:
np.dot(y,y) 

5

In [76]:
np.sqrt(np.dot(x,x))  *  np.sqrt(np.dot(y,y) )

7.071067811865476

In [58]:
np.sqrt(10 + 5)

3.872983346207417

In [77]:
5/7.071067811865476

0.7071067811865475

In [78]:
cosine_similarity(x, y)

0.7071067811865475

In [72]:
# Similarity Between Machine Learning and Others
print("ML - AI ",cosine_similarity(X[0],X[1]))
print("ML - Soccer ",cosine_similarity(X[0],X[2]))
print("ML - Cricket ",cosine_similarity(X[0],X[3]))
print("ML - Football ",cosine_similarity(X[0],X[4]))

ML - AI  0.9024488387562011
ML - Soccer  0.8036447564987467
ML - Cricket  0.8099714448530698
ML - Football  0.7785076546491277


In [75]:
# Distance Between Artificial Intelligence and others
print("AI - ML",cosine_similarity(X[1],X[0]))
print("AI - Soccer ",cosine_similarity(X[1],X[2]))
print("AI - Cricket ",cosine_similarity(X[1],X[3]))
print("AI - Football ",cosine_similarity(X[1],X[4]))

AI - ML 0.9024488387562011
AI - Soccer  0.8421931182069987
AI - Cricket  0.8517747494793314
AI - Football  0.8171600216120343


In [73]:
# Distance Between Soccer and others
print("Soccer - ML ",cosine_similarity(X[2],X[0]))
print("Soccer - AI ",cosine_similarity(X[2],X[1]))
print("Soccer - Cricket ",cosine_similarity(X[2],X[3]))
print("Soccer - Football ",cosine_similarity(X[2],X[4]))

Soccer - ML  0.8036447564987467
Soccer - AI  0.8421931182069987
Soccer - Cricket  0.9453677961961866
Soccer - Football  0.9443129867344253
