In [ ]:
Sentiment

1. Unsupervised - No Target - No Training - Rule based - find the label
2. Supervised - Target - Training - Manually Label the target - Text Classification

In [ ]:
1. Unsupervised - Rule Based 

In [ ]:
Lexicon-based sentiment analysis
1. TextBlob
2. Afinn
3. Vader

Readymade Solution

In [3]:
import textblob

In [ ]:
#https://github.com/sloria/TextBlob/blob/dev/src/textblob/en/en-sentiment.xml

In [5]:
textblob.TextBlob('The product is worst').sentiment.polarity

-1.0

In [19]:
import pandas as pd
import numpy as np

from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
~2900 words

In [7]:
reviews = pd.read_csv('movie_reviews.csv')

In [22]:
reviews['textblob_score'] = reviews['review'].apply(lambda x: textblob.TextBlob(x).sentiment.polarity)

In [23]:
reviews

review sentiment  \
0      One of the other reviewers has mentioned that ...  positive   
1      A wonderful little production. <br /><br />The...  positive   
2      I thought this was a wonderful way to spend ti...  positive   
3      Basically there's a family where a little boy ...  negative   
4      Petter Mattei's "Love in the Time of Money" is...  positive   
...                                                  ...       ...   
49995  I thought this movie did a down right good job...  positive   
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative   
49997  I am a Catholic taught in parochial elementary...  negative   
49998  I'm going to have to disagree with the previou...  negative   
49999  No one expects the Star Trek movies to be high...  negative   

       textblob_score textblob_sentiment  
0            0.023433           positive  
1            0.109722           positive  
2            0.354008           positive  
3           -0.057813           negative  
4            0.217952           positive  
...               ...                ...  
49995        0.394425           positive  
49996       -0.276190           negative  
49997        0.056984           negative  
49998       -0.048663           negative  
49999        0.120000           negative  

[50000 rows x 4 columns]

In [24]:
reviews['textblob_sentiment'] = np.where(reviews['textblob_score']<0, 'negative', 'positive')

In [39]:
reviews['review'].values[0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [26]:
confusion_matrix(reviews['sentiment']  ,reviews['textblob_sentiment'])

array([[10725, 14275],
       [ 1311, 23689]])

In [28]:
print("Text Blob Sentiment Accuracy : ",accuracy_score(reviews['sentiment']  ,reviews['textblob_sentiment']))

Text Blob Sentiment Accuracy :  0.68828


In [31]:
from afinn import Afinn

In [ ]:
#https://github.com/fnielsen/afinn/blob/master/afinn/data/AFINN-en-165.txt

In [ ]:
1. ~3200
2. More language
3. Emoticon support
4. Polarity score from -5 to +5

In [32]:
afinn = Afinn(emoticons=True)

In [40]:
afinn.score("""One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side. """)


-40.0

In [45]:
len("One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.")


1761

In [42]:
afinn.score("Excellent Excellent")

6.0

In [34]:
reviews['afinn_score'] = reviews['review'].apply(lambda x: afinn.score(x))

In [36]:
reviews['afinn_score']

0       -40.0
1        13.0
2        21.0
3        -8.0
4        28.0
         ... 
49995    27.0
49996   -12.0
49997    -7.0
49998    -6.0
49999    12.0
Name: afinn_score, Length: 50000, dtype: float64

In [43]:
reviews['#words'] = reviews['review'].apply(lambda x: len(x.split(' ')))

In [44]:
reviews

review sentiment  \
0      One of the other reviewers has mentioned that ...  positive   
1      A wonderful little production. <br /><br />The...  positive   
2      I thought this was a wonderful way to spend ti...  positive   
3      Basically there's a family where a little boy ...  negative   
4      Petter Mattei's "Love in the Time of Money" is...  positive   
...                                                  ...       ...   
49995  I thought this movie did a down right good job...  positive   
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative   
49997  I am a Catholic taught in parochial elementary...  negative   
49998  I'm going to have to disagree with the previou...  negative   
49999  No one expects the Star Trek movies to be high...  negative   

       textblob_score textblob_sentiment  afinn_score  #words  
0            0.023433           positive        -40.0     307  
1            0.109722           positive         13.0     162  
2            0.354008           positive         21.0     166  
3           -0.057813           negative         -8.0     138  
4            0.217952           positive         28.0     230  
...               ...                ...          ...     ...  
49995        0.394425           positive         27.0     194  
49996       -0.276190           negative        -12.0     112  
49997        0.056984           positive         -7.0     230  
49998       -0.048663           negative         -6.0     212  
49999        0.120000           positive         12.0     129  

[50000 rows x 6 columns]

In [47]:
reviews['afinn_score'] = reviews['afinn_score']/reviews['#words']

In [48]:
reviews

review sentiment  \
0      One of the other reviewers has mentioned that ...  positive   
1      A wonderful little production. <br /><br />The...  positive   
2      I thought this was a wonderful way to spend ti...  positive   
3      Basically there's a family where a little boy ...  negative   
4      Petter Mattei's "Love in the Time of Money" is...  positive   
...                                                  ...       ...   
49995  I thought this movie did a down right good job...  positive   
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative   
49997  I am a Catholic taught in parochial elementary...  negative   
49998  I'm going to have to disagree with the previou...  negative   
49999  No one expects the Star Trek movies to be high...  negative   

       textblob_score textblob_sentiment  afinn_score  #words  
0            0.023433           positive    -0.130293     307  
1            0.109722           positive     0.080247     162  
2            0.354008           positive     0.126506     166  
3           -0.057813           negative    -0.057971     138  
4            0.217952           positive     0.121739     230  
...               ...                ...          ...     ...  
49995        0.394425           positive     0.139175     194  
49996       -0.276190           negative    -0.107143     112  
49997        0.056984           positive    -0.030435     230  
49998       -0.048663           negative    -0.028302     212  
49999        0.120000           positive     0.093023     129  

[50000 rows x 6 columns]

In [49]:
reviews['afinn_sentiment'] = np.where(reviews['afinn_score']<0, 'negative', 'positive')

In [50]:
confusion_matrix(reviews['sentiment']  ,reviews['afinn_sentiment'])

array([[13583, 11417],
       [ 3444, 21556]])

In [51]:
print("Afinn Sentiment Accuracy : ",accuracy_score(reviews['sentiment']  ,reviews['afinn_sentiment']))

Afinn Sentiment Accuracy :  0.70278


In [ ]:
!pip install vaderSentiment

In [53]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

Total words and emoticons - ~ 7500
Polarity - -1 to +4
Sentiment score  - averaged on 10 sources

In [ ]:
#https://github.com/cjhutto/vaderSentiment/blob/master/vaderSentiment/vader_lexicon.txt

In [54]:
analyzer = SentimentIntensityAnalyzer()
vs = analyzer.polarity_scores("The product is excellent")
print("{:-<65} {}".format("The product is excellent", str(vs)))

The product is excellent----------------------------------------- {'neg': 0.0, 'neu': 0.448, 'pos': 0.552, 'compound': 0.5719}


In [56]:
reviews['vader_score'] = reviews['review'].apply(lambda x: analyzer.polarity_scores(x)['compound'])

In [57]:
reviews['vader_score']

0       -0.9916
1        0.9670
2        0.9519
3       -0.9213
4        0.9744
          ...  
49995    0.9886
49996   -0.6837
49997   -0.9734
49998   -0.8657
49999    0.6975
Name: vader_score, Length: 50000, dtype: float64

In [58]:
reviews['vader_sentiment'] = np.where(reviews['vader_score']<0, 'negative', 'positive')

In [61]:
confusion_matrix(reviews['sentiment']  ,reviews['vader_sentiment'])

array([[13253, 11747],
       [ 3468, 21532]])

In [62]:
print("Vader Sentiment Accuracy : ",accuracy_score(reviews['sentiment']  ,reviews['vader_sentiment']))

Vader Sentiment Accuracy :  0.6957
